// List of all Canadian cities (sample, can be expanded as needed)
export const CANADIAN_CITIES = [
    "Toronto",
    "Mississauga",
    "Brampton",
    "Markham",
    "Vaughan",
    "Richmond Hill",
    "Oakville",
    "Burlington",
    "Oshawa",
    "Whitby",
    "Ajax",
    "Pickering",
    "Milton",
    "Halton Hills",
    "Caledon",
    "Aurora",
    "Newmarket",
    "King",
    "East Gwillimbury",
    "Georgina",
    "Uxbridge",
    "Scugog",
    "Clarington",
    "Whitchurch-Stouffville",
    "Brock",
    "Waterloo",
    "Guelph",
    "Cambridge",
    "Kitchener",
    // ... rest of Canada
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Kitchener",
    "London",
    "Victoria",
    "Halifax",
    "Oshawa",
    "Windsor",
    "Saskatoon",
    "St. Catharines",
    "Regina",
    "St. John's",
    "Kelowna",
    "Barrie",
    "Sherbrooke",
    "Guelph",
    "Abbotsford",
    "Kingston",
    "Kanata",
    "Trois-Rivières",
    "Moncton",
    "Chicoutimi",
    "Milton",
    "Red Deer",
    "Brantford",
    "Thunder Bay",
    "White Rock",
    "Nanaimo",
    "Sudbury",
    "Lethbridge",
    "Saint John",
    "Peterborough",
    "Kamloops",
    "Sarnia",
    "Prince George",
    "Drummondville",
    "Fredericton",
    "Saint-Jérôme",
    "Chilliwack",
    "North Bay",
    "Granby",
    "Welland",
    "Belleville",
    "Charlottetown",
    // ... (add more as needed)
]; 