// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (takes precedence), then .env
config({ path: ".env.local" });
config({ path: ".env" });

// Supabase Prisma setup:
// - DATABASE_URL: Connection pooling (port 6543) - for application queries
// - DIRECT_URL: Direct connection (port 5432) - for migrations
// Both use the same pooler hostname but different ports
const databaseUrl = process.env["DATABASE_URL"];
const directUrl = process.env["DIRECT_URL"] || process.env["MIGRATE_DATABASE_URL"];

// For migrations, use DIRECT_URL if available, otherwise DATABASE_URL
const migrationUrl = directUrl || databaseUrl;

if (!migrationUrl) {
  console.error("❌ ERROR: DATABASE_URL is required!");
  console.error("   Add DATABASE_URL to your .env.local file");
  process.exit(1);
}

// Warn if DIRECT_URL is not set (migrations will be slower)
if (!directUrl && databaseUrl) {
  console.warn("⚠️  WARNING: DIRECT_URL not set. Migrations will use connection pooling (slower).");
  console.warn("   For better performance, add DIRECT_URL to .env.local:");
  console.warn('   DIRECT_URL="postgresql://postgres.bjtuzcmfqlqywiohcenr:[PASSWORD]@aws-0-ca-central-1.pooler.supabase.com:5432/postgres"');
  console.warn("");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationUrl,
    // Note: directUrl is not supported in prisma.config.ts for Prisma 7
    // It's only used via the schema file, but Prisma 7 doesn't allow url in schema
    // So we use DIRECT_URL for migrations and DATABASE_URL for client
  },
});
