services:
  # Full-stack application (Frontend + Backend)
  - type: web
    name: marcan-marketplace
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd server && npx prisma generate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRISMA_CLIENT_ENGINE_TYPE
        value: library
      - key: PRISMA_CLI_QUERY_ENGINE_TYPE
        value: binary
      - key: DATABASE_URL
        fromDatabase:
          name: marcan-db
          property: connectionString
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false

databases:
  - name: marcan-db
    databaseName: marcan
    user: marcan_user
    plan: free 