services:
  # Full-stack application (Frontend + Backend)
  - type: web
    name: marcan-marketplace
    env: node
    plan: free
    buildCommand: npm ci && cd client && npm ci && npm run build && cd ../server && npm ci
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: marcan-db
          property: connectionString
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false

databases:
  - name: marcan-db
    databaseName: marcan
    user: marcan_user
    plan: free 